### ISSUE TITLE
Better isDrupalRoot detection

### ISSUE THREAD

**Issue by e0ipso** [mateu-aguilo-bosch/drupal-unit-autoload#23]
Detecting based on `.txt` is not the usual practise.

cc @penyaskito

**Comment by penyaskito** [comment]
We should try to use same detection that drush uses.

See https://github.com/drush-ops/drush/blob/ff268e947949cc011b8a67472fad963908c05527/lib/Drush/Boot/DrupalBoot7.php#L7

**Comment by penyaskito** [comment]
Fixed.
